sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

before_install:
  - >
    if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update -y
      brew install poppler  # for pdfinfo
    else
      sudo apt-get update -y -qq
      sudo apt-get install -y -qq build-essential
      sudo apt-get install -y -qq poppler-utils  # for pdfinfo
    fi

install:
  - >
    if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew cask install -v mactex
      export PATH=/Library/TeX/texbin:$PATH
    else
      sudo apt-get install -y -qq texlive texlive-lang-cjk texlive-science texlive-fonts-recommended texlive-fonts-extra xdvik-ja dvipsk-ja gv latexmk
    fi

script:
  - make
  - pdfinfo main.pdf

branches:
  only:
    - master
