sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

before_script:
  - >
    if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update -y
      brew install homebrew/x11/xpdf  # for pdfinfo
    else
      sudo apt-get update -y -qq
      sudo apt-get install -y -qq build-essential
      sudo apt-get install -y -qq poppler-utils  # for pdfinfo
    fi

script:
  - make
  - pdfinfo main.pdf

branches:
  only:
    - master
